#!/bin/sh
### BEGIN INIT INFO
# Provides:		sound
# Required-Start:	$local_fs
#Required-Stop:		$local_fs
#Default-Start:		2 3 4 5
#Default-Stop:		0 1 6
#Short-Description:	Soundsensor
#Description:		Runs the Sound.py Script so that it can run in an init. d script. Use start, stop and status line to start, stop the script or look for it's status
### END INIT INFO
# /etc/init.d/sound

case "$1" in
	start)
	 echo  "Starting Soundsensor"
	 # run python soundsensor script from directory
	 python  /home/pi/Documents/Scripts/sound.py &
	 ;;
	stop)
	 echo "Stopping Soundsensor"
	 # kill the Soundsensor script 
	 killall python
	 ;;
	*)
	 echo "Usage /etc/init.d/Sound {start|stop} status not definded yet!"
	 exit 1
	 ;;
esac

exit 0 

